name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "GITHUB_WORKFLOW- $GITHUB_WORKFLOW"
    - run: echo "GITHUB_RUN_ID- $GITHUB_RUN_ID"
    - run: echo "GITHUB_RUN_NUMBER- $GITHUB_RUN_NUMBER"
    - run: echo "GITHUB_JOB- $GITHUB_JOB"
    - run: echo "GITHUB_REPOSITORY- $GITHUB_REPOSITORY"
    - run: echo "GITHUB_EVENT_NAME- $GITHUB_EVENT_NAME"
    - run: echo "GITHUB_WORKSPACE- $GITHUB_WORKSPACE"
    
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: alekzander7c4/lesson3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,$GITHUB_RUN_NUMBER"
