name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "DOCKER_TAG=0.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: alekzander7c4/lesson3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.DOCKER_TAG }}"


    - name: Run ansible playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: ansible.yaml
        # Optional, directory where playbooks live
        # directory: ./
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}

        inventory: |
          [aws:vars]
          ansible_user=ubuntu
        
          [aws]
          52.59.73.58
